CREATE OR REPLACE TABLE WAREHOUSE_DB.SILVER.CRM_CUST_INFO AS
SELECT * FROM WAREHOUSE_DB.BRONZE.CRM_CUST_INFO;

CREATE OR REPLACE TABLE WAREHOUSE_DB.SILVER.CRM_PRD_INFO AS
SELECT * FROM WAREHOUSE_DB.BRONZE.CRM_PRD_INFO;

CREATE OR REPLACE TABLE WAREHOUSE_DB.SILVER.ERP_CUST_AZ12 AS
SELECT * FROM WAREHOUSE_DB.BRONZE.ERP_CUST_AZ12;

CREATE OR REPLACE TABLE WAREHOUSE_DB.SILVER.ERP_LOC_A101 AS
SELECT * FROM WAREHOUSE_DB.BRONZE.ERP_LOC_A101;

CREATE OR REPLACE TABLE WAREHOUSE_DB.SILVER.ERP_PX_CAT_G1V2 AS
SELECT * FROM WAREHOUSE_DB.BRONZE.ERP_PX_CAT_G1V2;
